using System.Globalization;
using System.Text;
using Vela.Core.Diagnostics;
using Vela.Core.Lexing;
using Vela.Core.Source;
using Vela.Core.Syntax;

namespace Vela.Backend;

/// <summary>Performs Vela semantic checks while emitting deterministic, Native AOT-safe C#.</summary>
internal sealed class CSharpEmitter
{
    private static readonly string[] EmptyGenericNames = [];
    private static readonly HashSet<string> CSharpKeywords = new(StringComparer.Ordinal)
    {
        "abstract", "as", "base", "bool", "break", "byte", "case", "catch", "char", "checked", "class", "const", "continue",
        "decimal", "default", "delegate", "do", "double", "else", "enum", "event", "explicit", "extern", "false", "finally", "fixed",
        "float", "for", "foreach", "goto", "if", "implicit", "in", "int", "interface", "internal", "is", "lock", "long", "namespace",
        "new", "null", "object", "operator", "out", "override", "params", "private", "protected", "public", "readonly", "ref", "return",
        "sbyte", "sealed", "short", "sizeof", "stackalloc", "static", "string", "struct", "switch", "this", "throw", "true", "try",
        "typeof", "uint", "ulong", "unchecked", "unsafe", "ushort", "using", "virtual", "void", "volatile", "while"
    };

    private readonly SourceText _source;
    private readonly DiagnosticBag _diagnostics;
    private readonly CodeWriter _writer = new();
    private readonly Dictionary<string, FunctionSymbol> _functions = new(StringComparer.Ordinal);
    private readonly Dictionary<string, RecordSymbol> _records = new(StringComparer.Ordinal);

    public CSharpEmitter(SourceText source, DiagnosticBag diagnostics)
    {
        _source = source;
        _diagnostics = diagnostics;
    }

    public string Emit(CompilationUnitSyntax root)
    {
        RegisterDeclarations(root);

        _writer.WriteLine("// <auto-generated />");
        _writer.WriteLine("using System;");
        _writer.WriteLine("using System.Collections.Generic;");
        _writer.WriteLine("using Vela.Runtime;");
        _writer.WriteLine();
        _writer.WriteLine("namespace Vela.Generated;");
        _writer.WriteLine();

        foreach (var record in root.Members.OfType<RecordDeclarationSyntax>())
        {
            EmitRecord(record);
            _writer.WriteLine();
        }

        _writer.WriteLine("public static class Program");
        _writer.WriteLine("{");
        _writer.Indent();
        EmitEntryPoint(root);

        foreach (var function in root.Members.OfType<FunctionDeclarationSyntax>())
        {
            _writer.WriteLine();
            EmitFunction(function);
        }

        var topLevelStatements = root.Members.Where(static member => member is not FunctionDeclarationSyntax and not RecordDeclarationSyntax).ToArray();
        if (topLevelStatements.Length > 0)
        {
            _writer.WriteLine();
            EmitScript(topLevelStatements);
        }

        _writer.Unindent();
        _writer.WriteLine("}");
        _writer.WriteLine("#line default");
        return _writer.ToString();
    }

    private void RegisterDeclarations(CompilationUnitSyntax root)
    {
        foreach (var member in root.Members)
        {
            switch (member)
            {
                case FunctionDeclarationSyntax function:
                    AddDeclaration(_functions, function.Identifier.Text, new FunctionSymbol(function), function.Identifier.Span, "function");
                    break;
                case RecordDeclarationSyntax record:
                    AddDeclaration(_records, record.Identifier.Text, new RecordSymbol(record), record.Identifier.Span, "record");
                    break;
            }
        }
    }

    private void AddDeclaration<TSymbol>(Dictionary<string, TSymbol> symbols, string name, TSymbol symbol, TextSpan span, string kind)
    {
        if (!symbols.TryAdd(name, symbol))
        {
            Report("VEL3000", span, $"Duplicate {kind} declaration '{name}'.", "Rename one declaration so every symbol in this scope is unique.");
        }
    }

    private void EmitEntryPoint(CompilationUnitSyntax root)
    {
        _writer.WriteLine("public static int Main(string[] args)");
        _writer.WriteLine("{");
        _writer.Indent();

        if (_functions.TryGetValue("main", out var main))
        {
            if (main.Syntax.Parameters.Count != 0)
            {
                Report("VEL3006", main.Syntax.Identifier.Span, "The entry function 'main' cannot declare parameters.", "Declare 'fn main() -> Int:' without parameters.");
            }

            if (main.GenericNames.Length != 0)
            {
                Report("VEL3006", main.Syntax.Identifier.Span, "The entry function 'main' cannot declare generic parameters.", "Declare a non-generic 'fn main() -> Int:'.");
            }

            var returnType = ResolveType(main.Syntax.ReturnType, main.GenericNames, main.Syntax.Identifier.Span, defaultType: VelaType.WholeNumber);
            if (!returnType.IsSameAs(VelaType.WholeNumber))
            {
                Report("VEL3007", main.Syntax.Identifier.Span, "The entry function 'main' must return Int.", "Change the declaration to 'fn main() -> Int:'.");
            }

            _writer.WriteLine("return checked((int)main());");
        }
        else if (root.Members.Any(static member => member is not FunctionDeclarationSyntax and not RecordDeclarationSyntax))
        {
            _writer.WriteLine("return __script();");
        }
        else
        {
            _writer.WriteLine("return 0;");
        }

        _writer.Unindent();
        _writer.WriteLine("}");
    }

    private void EmitRecord(RecordDeclarationSyntax record)
    {
        var symbol = _records[record.Identifier.Text];
        var genericNames = symbol.GenericNames;
        var fields = record.Members.OfType<RecordFieldSyntax>().ToArray();

        foreach (var method in record.Members.OfType<RecordMethodSyntax>())
        {
            Report("VEL3010", method.Span, "Record methods are not available in this compiler version.", "Move the behavior to a generic function and pass the record as an argument.");
        }

        WriteLineDirective(record);
        var genericSuffix = FormatGenericParameterNames(genericNames);
        var parameters = string.Join(", ", fields.Select(field =>
            $"{CSharpType(ResolveType(field.Type, genericNames, field.Type.Span))} {EscapeIdentifier(field.Identifier.Text)}"));
        _writer.WriteLine($"public sealed record {EscapeIdentifier(record.Identifier.Text)}{genericSuffix}({parameters});");
    }

    private void EmitFunction(FunctionDeclarationSyntax function)
    {
        var symbol = _functions[function.Identifier.Text];
        var genericNames = symbol.GenericNames;
        ValidateGenericConstraints(function.GenericParameters);
        var returnType = ResolveType(function.ReturnType, genericNames, function.Identifier.Span, defaultType: VelaType.Unit);
        var parameters = new List<string>();
        var scope = new Scope(null);

        foreach (var parameter in function.Parameters)
        {
            var parameterType = ResolveType(parameter.Type, genericNames, parameter.Type.Span);
            AddVariable(scope, parameter.Identifier.Text, new VariableSymbol(parameterType, false), parameter.Identifier.Span);
            parameters.Add($"{CSharpType(parameterType)} {EscapeIdentifier(parameter.Identifier.Text)}");
        }

        WriteLineDirective(function);
        _writer.WriteLine($"private static {CSharpType(returnType)} {EscapeIdentifier(function.Identifier.Text)}{FormatGenericParameterNames(genericNames)}({string.Join(", ", parameters)})");
        _writer.WriteLine("{");
        _writer.Indent();
        var alwaysReturns = EmitBlock(function.Body, scope, returnType, isTailBlock: true);
        if (!alwaysReturns && !returnType.IsSameAs(VelaType.Unit))
        {
            Report("VEL3007", function.Identifier.Span, $"Function '{function.Identifier.Text}' does not return {returnType} on every path.", "Return a value explicitly or end every control-flow branch with an expression.");
            _writer.WriteLine($"return {DefaultValue(returnType)};");
        }
        else if (!alwaysReturns && returnType.IsSameAs(VelaType.Unit))
        {
            _writer.WriteLine("return;");
        }

        _writer.Unindent();
        _writer.WriteLine("}");
    }

    private void EmitScript(IReadOnlyList<StatementSyntax> statements)
    {
        _writer.WriteLine("private static int __script()");
        _writer.WriteLine("{");
        _writer.Indent();
        var scope = new Scope(null);
        _ = EmitStatements(statements, scope, VelaType.WholeNumber, tailReturnsValue: false);
        _writer.WriteLine("return 0;");
        _writer.Unindent();
        _writer.WriteLine("}");
    }

    private bool EmitBlock(BlockSyntax block, Scope parent, VelaType returnType, bool isTailBlock)
    {
        var scope = new Scope(parent);
        return EmitStatements(block.Statements, scope, returnType, isTailBlock);
    }

    private bool EmitStatements(IReadOnlyList<StatementSyntax> statements, Scope scope, VelaType returnType, bool tailReturnsValue)
    {
        for (var index = 0; index < statements.Count; index++)
        {
            var isTail = tailReturnsValue && index == statements.Count - 1;
            var returns = EmitStatement(statements[index], scope, returnType, isTail);
            if (returns && index < statements.Count - 1)
            {
                Report("VEL3011", statements[index + 1].Span, "Unreachable statement after a return.", "Remove the statement or move it before the return.");
            }

            if (isTail)
            {
                return returns;
            }
        }

        return false;
    }

    private bool EmitStatement(StatementSyntax statement, Scope scope, VelaType returnType, bool isTail)
    {
        WriteLineDirective(statement);
        switch (statement)
        {
            case LetStatementSyntax let:
                EmitVariable(let.Identifier.Text, let.Type, let.Initializer, false, scope, let.Span);
                return false;
            case VarStatementSyntax variable:
                EmitVariable(variable.Identifier.Text, variable.Type, variable.Initializer, true, scope, variable.Span);
                return false;
            case ReturnStatementSyntax returnStatement:
                EmitReturn(returnStatement, scope, returnType);
                return true;
            case ExpressionStatementSyntax expressionStatement:
                return EmitExpressionStatement(expressionStatement.Expression, scope, returnType, isTail);
            case IfStatementSyntax conditional:
                return EmitIf(conditional, scope, returnType, isTail);
            case FunctionDeclarationSyntax:
            case RecordDeclarationSyntax:
                Report("VEL3012", statement.Span, "Declarations are only allowed at the top level.", "Move this declaration outside the current function or block.");
                return false;
            default:
                Report("VEL3013", statement.Span, "Unsupported statement.");
                return false;
        }
    }

    private void EmitVariable(string name, TypeSyntax? declaredTypeSyntax, ExpressionSyntax initializer, bool mutable, Scope scope, TextSpan span)
    {
        var initializerResult = EmitExpression(initializer, scope);
        var declaredType = declaredTypeSyntax is null
            ? initializerResult.Type
            : ResolveType(declaredTypeSyntax, EmptyGenericNames, declaredTypeSyntax.Span);
        EnsureAssignable(declaredType, initializerResult.Type, initializer.Span);
        AddVariable(scope, name, new VariableSymbol(declaredType, mutable), span);
        _writer.WriteLine($"{CSharpType(declaredType)} {EscapeIdentifier(name)} = {initializerResult.Code};");
    }

    private void EmitReturn(ReturnStatementSyntax statement, Scope scope, VelaType returnType)
    {
        if (statement.Expression is null)
        {
            if (!returnType.IsSameAs(VelaType.Unit))
            {
                Report("VEL3007", statement.ReturnKeyword.Span, $"A function returning {returnType} requires a value.", "Return an expression with the declared return type.");
            }

            _writer.WriteLine("return;");
            return;
        }

        var expression = EmitExpression(statement.Expression, scope);
        EnsureAssignable(returnType, expression.Type, statement.Expression.Span);
        _writer.WriteLine($"return {expression.Code};");
    }

    private bool EmitExpressionStatement(ExpressionSyntax expression, Scope scope, VelaType returnType, bool isTail)
    {
        var result = EmitExpression(expression, scope);
        if (isTail && !returnType.IsSameAs(VelaType.Unit))
        {
            EnsureAssignable(returnType, result.Type, expression.Span);
            _writer.WriteLine($"return {result.Code};");
            return true;
        }

        _writer.WriteLine($"{result.Code};");
        return false;
    }

    private bool EmitIf(IfStatementSyntax conditional, Scope scope, VelaType returnType, bool isTail)
    {
        var condition = EmitExpression(conditional.Condition, scope);
        EnsureAssignable(VelaType.Bool, condition.Type, conditional.Condition.Span);
        _writer.WriteLine($"if ({condition.Code})");
        _writer.WriteLine("{");
        _writer.Indent();
        var thenReturns = EmitBlock(conditional.ThenBlock, scope, returnType, isTail);
        _writer.Unindent();
        _writer.WriteLine("}");

        if (conditional.ElseClause is null)
        {
            return false;
        }

        _writer.WriteLine("else");
        _writer.WriteLine("{");
        _writer.Indent();
        var elseReturns = EmitBlock(conditional.ElseClause.Block, scope, returnType, isTail);
        _writer.Unindent();
        _writer.WriteLine("}");
        return isTail && thenReturns && elseReturns;
    }

    private ExpressionResult EmitExpression(ExpressionSyntax expression, Scope scope)
    {
        return expression switch
        {
            LiteralExpressionSyntax literal => EmitLiteral(literal),
            NameExpressionSyntax name => EmitName(name, scope),
            MemberAccessExpressionSyntax member => EmitMember(member, scope),
            UnaryExpressionSyntax unary => EmitUnary(unary, scope),
            BinaryExpressionSyntax binary => EmitBinary(binary, scope),
            AssignmentExpressionSyntax assignment => EmitAssignment(assignment, scope),
            ParenthesizedExpressionSyntax parenthesized => EmitParenthesized(parenthesized, scope),
            CallExpressionSyntax call => EmitCall(call, scope),
            ListExpressionSyntax list => EmitList(list, scope),
            _ => UnsupportedExpression(expression)
        };
    }

    private ExpressionResult EmitLiteral(LiteralExpressionSyntax literal)
    {
        var token = literal.LiteralToken;
        return token.Kind switch
        {
            TokenKind.IntegerLiteral => new ExpressionResult(VelaType.WholeNumber, $"{token.Text}L"),
            TokenKind.FloatLiteral => new ExpressionResult(VelaType.FloatingPoint, $"{token.Text}d"),
            TokenKind.StringLiteral => new ExpressionResult(VelaType.Text, QuoteString((string?)token.Value ?? string.Empty)),
            TokenKind.TrueKeyword => new ExpressionResult(VelaType.Bool, "true"),
            TokenKind.FalseKeyword => new ExpressionResult(VelaType.Bool, "false"),
            TokenKind.NilKeyword => new ExpressionResult(VelaType.Nil, "null"),
            _ => UnsupportedExpression(literal)
        };
    }

    private ExpressionResult EmitName(NameExpressionSyntax name, Scope scope)
    {
        if (scope.TryLookup(name.Identifier.Text, out var variable))
        {
            return new ExpressionResult(variable.Type, EscapeIdentifier(name.Identifier.Text));
        }

        if (_functions.ContainsKey(name.Identifier.Text) || _records.ContainsKey(name.Identifier.Text))
        {
            return new ExpressionResult(VelaType.Unknown, EscapeIdentifier(name.Identifier.Text));
        }

        Report("VEL3001", name.Span, $"Unknown name '{name.Identifier.Text}'.", "Declare the name before using it or correct the spelling.");
        return new ExpressionResult(VelaType.Unknown, EscapeIdentifier(name.Identifier.Text));
    }

    private ExpressionResult EmitMember(MemberAccessExpressionSyntax member, Scope scope)
    {
        var receiver = EmitExpression(member.Receiver, scope);
        if (_records.TryGetValue(receiver.Type.Name, out var record))
        {
            var field = record.Syntax.Members.OfType<RecordFieldSyntax>().FirstOrDefault(candidate => candidate.Identifier.Text == member.Member.Text);
            if (field is not null)
            {
                var substitutions = CreateGenericSubstitutions(record.GenericNames, receiver.Type.TypeArguments.ToArray());
                var fieldType = ResolveType(field.Type, record.GenericNames, field.Type.Span).Substitute(substitutions);
                return new ExpressionResult(fieldType, $"{receiver.Code}.{EscapeIdentifier(member.Member.Text)}");
            }
        }

        Report("VEL3009", member.Member.Span, $"Type '{receiver.Type}' does not contain member '{member.Member.Text}'.", "Use a declared record field or correct the member name.");
        return new ExpressionResult(VelaType.Unknown, $"{receiver.Code}.{EscapeIdentifier(member.Member.Text)}");
    }

    private ExpressionResult EmitUnary(UnaryExpressionSyntax unary, Scope scope)
    {
        var operand = EmitExpression(unary.Operand, scope);
        if (unary.OperatorToken.Kind == TokenKind.Minus && operand.Type.IsNumeric)
        {
            return new ExpressionResult(operand.Type, $"-{operand.Code}");
        }

        Report("VEL3002", unary.Span, $"Operator '{unary.OperatorToken.Text}' cannot be applied to {operand.Type}.");
        return new ExpressionResult(VelaType.Unknown, $"{unary.OperatorToken.Text}{operand.Code}");
    }

    private ExpressionResult EmitBinary(BinaryExpressionSyntax binary, Scope scope)
    {
        var left = EmitExpression(binary.Left, scope);
        var right = EmitExpression(binary.Right, scope);
        var operation = binary.OperatorToken.Kind;

        if (operation is TokenKind.EqualsEquals or TokenKind.BangEquals)
        {
            EnsureComparable(left.Type, right.Type, binary.Span);
            return new ExpressionResult(VelaType.Bool, $"{left.Code} {binary.OperatorToken.Text} {right.Code}");
        }

        if (operation is TokenKind.Less or TokenKind.LessOrEqual or TokenKind.Greater or TokenKind.GreaterOrEqual)
        {
            if (!left.Type.IsNumeric || !right.Type.IsNumeric)
            {
                Report("VEL3002", binary.Span, $"Operator '{binary.OperatorToken.Text}' requires numeric operands.");
            }

            return new ExpressionResult(VelaType.Bool, $"{left.Code} {binary.OperatorToken.Text} {right.Code}");
        }

        if (operation == TokenKind.Plus && left.Type.IsSameAs(VelaType.Text) && right.Type.IsSameAs(VelaType.Text))
        {
            return new ExpressionResult(VelaType.Text, $"{left.Code} + {right.Code}");
        }

        if (left.Type.IsNumeric && right.Type.IsNumeric)
        {
            var type = left.Type.IsSameAs(VelaType.FloatingPoint) || right.Type.IsSameAs(VelaType.FloatingPoint) ? VelaType.FloatingPoint : VelaType.WholeNumber;
            return new ExpressionResult(type, $"{left.Code} {binary.OperatorToken.Text} {right.Code}");
        }

        Report("VEL3002", binary.Span, $"Operator '{binary.OperatorToken.Text}' cannot be applied to {left.Type} and {right.Type}.");
        return new ExpressionResult(VelaType.Unknown, $"{left.Code} {binary.OperatorToken.Text} {right.Code}");
    }

    private ExpressionResult EmitAssignment(AssignmentExpressionSyntax assignment, Scope scope)
    {
        if (assignment.Target is not NameExpressionSyntax target)
        {
            Report("VEL3004", assignment.Target.Span, "Only named mutable bindings can be assigned.", "Assign to a variable declared with 'var'.");
            return new ExpressionResult(VelaType.Unknown, "default");
        }

        var value = EmitExpression(assignment.Value, scope);
        if (!scope.TryLookup(target.Identifier.Text, out var variable))
        {
            Report("VEL3001", target.Span, $"Unknown name '{target.Identifier.Text}'.", "Declare the variable before assigning to it.");
            return new ExpressionResult(VelaType.Unknown, $"{EscapeIdentifier(target.Identifier.Text)} = {value.Code}");
        }

        if (!variable.Mutable)
        {
            Report("VEL3004", target.Span, $"Cannot assign to immutable binding '{target.Identifier.Text}'.", "Declare the binding with 'var' if it must change.");
        }

        EnsureAssignable(variable.Type, value.Type, assignment.Value.Span);
        return new ExpressionResult(variable.Type, $"{EscapeIdentifier(target.Identifier.Text)} = {value.Code}");
    }

    private ExpressionResult EmitParenthesized(ParenthesizedExpressionSyntax expression, Scope scope)
    {
        var inner = EmitExpression(expression.Expression, scope);
        return new ExpressionResult(inner.Type, $"({inner.Code})");
    }

    private ExpressionResult EmitCall(CallExpressionSyntax call, Scope scope)
    {
        if (call.Callee is not NameExpressionSyntax name)
        {
            Report("VEL3005", call.Callee.Span, "Only named functions and records can be called.");
            return new ExpressionResult(VelaType.Unknown, "default");
        }

        var arguments = call.Arguments.Select(argument => EmitExpression(argument, scope)).ToArray();
        var explicitTypes = call.TypeArguments.Select(type => ResolveType(type, EmptyGenericNames, type.Span)).ToArray();
        if (name.Identifier.Text == "print")
        {
            if (arguments.Length != 1)
            {
                Report("VEL3006", call.Span, "Function 'print' expects exactly one argument.");
            }

            var printedValue = arguments.Length == 0 ? "string.Empty" : arguments[0].Code;
            return new ExpressionResult(VelaType.Unit, $"Console.WriteLine({printedValue})");
        }

        if (_functions.TryGetValue(name.Identifier.Text, out var function))
        {
            return EmitFunctionCall(call, function, arguments, explicitTypes);
        }

        if (_records.TryGetValue(name.Identifier.Text, out var record))
        {
            return EmitRecordConstruction(call, record, arguments, explicitTypes);
        }

        Report("VEL3005", name.Span, $"Unknown function or record '{name.Identifier.Text}'.", "Declare it before calling it or correct the spelling.");
        return new ExpressionResult(VelaType.Unknown, $"{EscapeIdentifier(name.Identifier.Text)}({string.Join(", ", arguments.Select(static argument => argument.Code))})");
    }

    private ExpressionResult EmitFunctionCall(CallExpressionSyntax call, FunctionSymbol function, ExpressionResult[] arguments, VelaType[] explicitTypes)
    {
        if (arguments.Length != function.Syntax.Parameters.Count)
        {
            Report("VEL3006", call.Span, $"Function '{function.Syntax.Identifier.Text}' expects {function.Syntax.Parameters.Count} argument(s), but received {arguments.Length}.");
        }

        var substitutions = CreateGenericSubstitutions(function.GenericNames, explicitTypes);
        if (explicitTypes.Length > 0 && explicitTypes.Length != function.GenericNames.Length)
        {
            Report("VEL3006", call.Span, $"Function '{function.Syntax.Identifier.Text}' expects {function.GenericNames.Length} type argument(s), but received {explicitTypes.Length}.");
        }

        for (var index = 0; index < Math.Min(arguments.Length, function.Syntax.Parameters.Count); index++)
        {
            var expected = ResolveType(function.Syntax.Parameters[index].Type, function.GenericNames, function.Syntax.Parameters[index].Type.Span);
            InferGenericArguments(expected, arguments[index].Type, function.GenericNames, substitutions);
        }

        foreach (var genericName in function.GenericNames)
        {
            if (!substitutions.ContainsKey(genericName))
            {
                Report("VEL3006", call.Span, $"Cannot infer generic type parameter '{genericName}' for function '{function.Syntax.Identifier.Text}'.", "Supply an explicit type argument.");
                substitutions[genericName] = VelaType.Unknown;
            }
        }

        for (var index = 0; index < Math.Min(arguments.Length, function.Syntax.Parameters.Count); index++)
        {
            var expected = ResolveType(function.Syntax.Parameters[index].Type, function.GenericNames, function.Syntax.Parameters[index].Type.Span).Substitute(substitutions);
            EnsureAssignable(expected, arguments[index].Type, call.Arguments[index].Span);
        }

        var returnType = ResolveType(function.Syntax.ReturnType, function.GenericNames, function.Syntax.Identifier.Span, defaultType: VelaType.Unit).Substitute(substitutions);
        var typeArguments = explicitTypes.Length > 0
            ? $"<{string.Join(", ", explicitTypes.Select(CSharpType))}>"
            : string.Empty;
        var code = $"{EscapeIdentifier(function.Syntax.Identifier.Text)}{typeArguments}({string.Join(", ", arguments.Select(static argument => argument.Code))})";
        return new ExpressionResult(returnType, code);
    }

    private ExpressionResult EmitRecordConstruction(CallExpressionSyntax call, RecordSymbol record, ExpressionResult[] arguments, VelaType[] explicitTypes)
    {
        var fields = record.Syntax.Members.OfType<RecordFieldSyntax>().ToArray();
        if (arguments.Length != fields.Length)
        {
            Report("VEL3006", call.Span, $"Record '{record.Syntax.Identifier.Text}' expects {fields.Length} value(s), but received {arguments.Length}.");
        }

        var substitutions = CreateGenericSubstitutions(record.GenericNames, explicitTypes);
        for (var index = 0; index < Math.Min(arguments.Length, fields.Length); index++)
        {
            var expected = ResolveType(fields[index].Type, record.GenericNames, fields[index].Type.Span);
            InferGenericArguments(expected, arguments[index].Type, record.GenericNames, substitutions);
        }

        foreach (var genericName in record.GenericNames)
        {
            if (!substitutions.ContainsKey(genericName))
            {
                Report("VEL3006", call.Span, $"Cannot infer generic type parameter '{genericName}' for record '{record.Syntax.Identifier.Text}'.", "Supply an explicit type argument.");
                substitutions[genericName] = VelaType.Unknown;
            }
        }

        for (var index = 0; index < Math.Min(arguments.Length, fields.Length); index++)
        {
            var expected = ResolveType(fields[index].Type, record.GenericNames, fields[index].Type.Span).Substitute(substitutions);
            EnsureAssignable(expected, arguments[index].Type, call.Arguments[index].Span);
        }

        var constructedType = new VelaType(record.Syntax.Identifier.Text, record.GenericNames.Select(name => substitutions.TryGetValue(name, out var type) ? type : VelaType.Unknown).ToArray());
        var typeArguments = constructedType.TypeArguments.Count == 0 ? string.Empty : $"<{string.Join(", ", constructedType.TypeArguments.Select(CSharpType))}>";
        var code = $"new {EscapeIdentifier(record.Syntax.Identifier.Text)}{typeArguments}({string.Join(", ", arguments.Select(static argument => argument.Code))})";
        return new ExpressionResult(constructedType, code);
    }

    private ExpressionResult EmitList(ListExpressionSyntax list, Scope scope)
    {
        var elements = list.Elements.Select(element => EmitExpression(element, scope)).ToArray();
        var elementType = elements.Length == 0 ? VelaType.Unknown : elements[0].Type;
        foreach (var element in elements.Skip(1))
        {
            EnsureAssignable(elementType, element.Type, list.Span);
        }

        if (elementType.IsUnknown)
        {
            Report("VEL3006", list.Span, "Cannot infer the type of an empty list.", "Add at least one element or use an explicitly typed variable.");
        }

        return new ExpressionResult(
            new VelaType("List", [elementType]),
            $"new List<{CSharpType(elementType)}> {{ {string.Join(", ", elements.Select(static element => element.Code))} }}");
    }

    private ExpressionResult UnsupportedExpression(ExpressionSyntax expression)
    {
        Report("VEL3013", expression.Span, "Unsupported expression.");
        return new ExpressionResult(VelaType.Unknown, "default");
    }

    private VelaType ResolveType(TypeSyntax? syntax, IReadOnlyCollection<string> genericNames, TextSpan span, VelaType? defaultType = null)
    {
        if (syntax is null)
        {
            return defaultType ?? VelaType.Unknown;
        }

        if (syntax is not NamedTypeSyntax named)
        {
            Report("VEL3013", syntax.Span, "Unsupported type syntax.");
            return VelaType.Unknown;
        }

        var arguments = named.TypeArguments.Select(argument => ResolveType(argument, genericNames, argument.Span)).ToArray();
        var type = named.Identifier.Text switch
        {
            "Int" => VelaType.WholeNumber,
            "Float" => VelaType.FloatingPoint,
            "Bool" => VelaType.Bool,
            "Text" => VelaType.Text,
            "Unit" => VelaType.Unit,
            "List" or "Result" or "Option" => new VelaType(named.Identifier.Text, arguments),
            _ when genericNames.Contains(named.Identifier.Text) && arguments.Length == 0 => new VelaType(named.Identifier.Text),
            _ when _records.ContainsKey(named.Identifier.Text) => new VelaType(named.Identifier.Text, arguments),
            _ => ReportUnknownType(named)
        };

        ValidateTypeArgumentCount(type, named.Span, arguments.Length);
        if (named.QuestionToken is not null)
        {
            type = new VelaType("Option", [type]);
        }

        return type;
    }

    private VelaType ReportUnknownType(NamedTypeSyntax named)
    {
        Report("VEL3001", named.Span, $"Unknown type '{named.Identifier.Text}'.", "Use a built-in type, a generic parameter, or a declared record.");
        return VelaType.Unknown;
    }

    private void ValidateTypeArgumentCount(VelaType type, TextSpan span, int actualCount)
    {
        int expected = type.Name switch
        {
            "List" or "Option" => 1,
            "Result" => 2,
            _ when _records.TryGetValue(type.Name, out var record) => record.GenericNames.Length,
            _ => 0
        };

        if (type.Name != "<unknown>" && actualCount != expected)
        {
            Report("VEL3006", span, $"Type '{type.Name}' expects {expected} type argument(s), but received {actualCount}.");
        }
    }

    private void ValidateGenericConstraints(IReadOnlyList<GenericParameterSyntax> parameters)
    {
        foreach (var parameter in parameters.Where(static parameter => parameter.Constraint is not null))
        {
            Report("VEL3010", parameter.Span, $"Generic constraint on '{parameter.Identifier.Text}' is not available in this compiler version.", "Remove the constraint or enforce it through a runtime contract.");
        }
    }

    private void InferGenericArguments(VelaType expected, VelaType actual, IReadOnlyCollection<string> genericNames, IDictionary<string, VelaType> substitutions)
    {
        if (genericNames.Contains(expected.Name) && expected.TypeArguments.Count == 0)
        {
            if (substitutions.TryGetValue(expected.Name, out var existing))
            {
                EnsureAssignable(existing, actual, default);
            }
            else
            {
                substitutions[expected.Name] = actual;
            }

            return;
        }

        if (expected.Name != actual.Name || expected.TypeArguments.Count != actual.TypeArguments.Count)
        {
            return;
        }

        for (var index = 0; index < expected.TypeArguments.Count; index++)
        {
            InferGenericArguments(expected.TypeArguments[index], actual.TypeArguments[index], genericNames, substitutions);
        }
    }

    private static Dictionary<string, VelaType> CreateGenericSubstitutions(string[] genericNames, VelaType[] explicitTypes)
    {
        var substitutions = new Dictionary<string, VelaType>(StringComparer.Ordinal);
        for (var index = 0; index < Math.Min(genericNames.Length, explicitTypes.Length); index++)
        {
            substitutions[genericNames[index]] = explicitTypes[index];
        }

        return substitutions;
    }

    private void EnsureAssignable(VelaType expected, VelaType actual, TextSpan span)
    {
        if (expected.IsUnknown || actual.IsUnknown || expected.IsSameAs(actual) || (expected.IsSameAs(VelaType.FloatingPoint) && actual.IsSameAs(VelaType.WholeNumber)) || (actual.IsSameAs(VelaType.Nil) && (expected.IsSameAs(VelaType.Text) || expected.IsOptional)))
        {
            return;
        }

        Report("VEL3002", span, $"Type mismatch: expected {expected}, found {actual}.", "Change the value or update the declared type.");
    }

    private void EnsureComparable(VelaType left, VelaType right, TextSpan span)
    {
        if (left.IsUnknown || right.IsUnknown || left.IsSameAs(right) || (left.IsNumeric && right.IsNumeric) || left.IsSameAs(VelaType.Nil) || right.IsSameAs(VelaType.Nil))
        {
            return;
        }

        Report("VEL3002", span, $"Values of type {left} and {right} cannot be compared.");
    }

    private void AddVariable(Scope scope, string name, VariableSymbol symbol, TextSpan span)
    {
        if (!scope.TryAdd(name, symbol))
        {
            Report("VEL3000", span, $"Duplicate local binding '{name}'.", "Use a distinct name in this scope.");
        }
    }

    private void WriteLineDirective(SyntaxNode syntax)
    {
        var location = _source.GetLocation(syntax.Span);
        var path = _source.FilePath.Replace("\\", "\\\\", StringComparison.Ordinal).Replace("\"", "\\\"", StringComparison.Ordinal);
        _writer.WriteLine($"#line {location.Line.ToString(CultureInfo.InvariantCulture)} \"{path}\"");
    }

    private static string CSharpType(VelaType type) => type.Name switch
    {
        "Int" => "long",
        "Float" => "double",
        "Bool" => "bool",
        "Text" => "string",
        "Unit" => "void",
        "Option" when type.TypeArguments.Count == 1 => $"Option<{CSharpType(type.TypeArguments[0])}>",
        "Result" when type.TypeArguments.Count == 2 => $"Result<{CSharpType(type.TypeArguments[0])}, {CSharpType(type.TypeArguments[1])}>",
        "List" when type.TypeArguments.Count == 1 => $"List<{CSharpType(type.TypeArguments[0])}>",
        "Nil" => "object?",
        "<unknown>" => "object",
        _ when type.TypeArguments.Count == 0 => EscapeIdentifier(type.Name),
        _ => $"{EscapeIdentifier(type.Name)}<{string.Join(", ", type.TypeArguments.Select(CSharpType))}>"
    };

    private static string DefaultValue(VelaType type) => type.Name switch
    {
        "Int" => "0L",
        "Float" => "0d",
        "Bool" => "false",
        "Text" => "string.Empty",
        _ => "default!"
    };

    private static string FormatGenericParameterNames(string[] names) => names.Length == 0
        ? string.Empty
        : $"<{string.Join(", ", names.Select(EscapeIdentifier))}>";

    private static string QuoteString(string value)
    {
        var builder = new StringBuilder(value.Length + 2);
        builder.Append('"');
        foreach (var character in value)
        {
            _ = character switch
            {
                '\\' => builder.Append("\\\\"),
                '"' => builder.Append("\\\""),
                '\n' => builder.Append("\\n"),
                '\r' => builder.Append("\\r"),
                '\t' => builder.Append("\\t"),
                _ when char.IsControl(character) => builder.Append("\\u").Append(((int)character).ToString("x4", CultureInfo.InvariantCulture)),
                _ => builder.Append(character)
            };
        }

        builder.Append('"');
        return builder.ToString();
    }

    private static string EscapeIdentifier(string identifier) => CSharpKeywords.Contains(identifier) ? $"@{identifier}" : identifier;

    private void Report(string code, TextSpan span, string message, string? help = null) => _diagnostics.ReportError(code, span, message, help);

    private sealed record ExpressionResult(VelaType Type, string Code);

    private sealed record VariableSymbol(VelaType Type, bool Mutable);

    private sealed record FunctionSymbol(FunctionDeclarationSyntax Syntax)
    {
        public string[] GenericNames { get; } = Syntax.GenericParameters.Select(static parameter => parameter.Identifier.Text).ToArray();
    }

    private sealed record RecordSymbol(RecordDeclarationSyntax Syntax)
    {
        public string[] GenericNames { get; } = Syntax.GenericParameters.Select(static parameter => parameter.Identifier.Text).ToArray();
    }

    private sealed class Scope(Scope? parent)
    {
        private readonly Dictionary<string, VariableSymbol> _variables = new(StringComparer.Ordinal);

        public bool TryAdd(string name, VariableSymbol symbol) => _variables.TryAdd(name, symbol);

        public bool TryLookup(string name, out VariableSymbol symbol)
        {
            if (_variables.TryGetValue(name, out symbol!))
            {
                return true;
            }

            return parent is not null && parent.TryLookup(name, out symbol!);
        }
    }
}
