using System.Globalization;
using System.Text;
using Vela.Core.Diagnostics;
using Vela.Core.Lexing;
using Vela.Core.Source;
using Vela.Core.Syntax;

namespace Vela.Backend;

/// <summary>Performs Vela semantic checks while emitting deterministic, Native AOT-safe C#.</summary>
internal sealed class CSharpEmitter
{
    private static readonly string[] EmptyGenericNames = [];
    private static readonly HashSet<string> CSharpKeywords = new(StringComparer.Ordinal)
    {
        "abstract", "as", "base", "bool", "break", "byte", "case", "catch", "char", "checked", "class", "const", "continue",
        "decimal", "default", "delegate", "do", "double", "else", "enum", "event", "explicit", "extern", "false", "finally", "fixed",
        "float", "for", "foreach", "goto", "if", "implicit", "in", "int", "interface", "internal", "is", "lock", "long", "namespace",
        "new", "null", "object", "operator", "out", "override", "params", "private", "protected", "public", "readonly", "ref", "return",
        "sbyte", "sealed", "short", "sizeof", "stackalloc", "static", "string", "struct", "switch", "this", "throw", "true", "try",
        "typeof", "uint", "ulong", "unchecked", "unsafe", "ushort", "using", "virtual", "void", "volatile", "while"
    };

    private readonly SourceText _source;
    private readonly DiagnosticBag _diagnostics;
    private readonly CodeWriter _writer = new();
    private readonly Dictionary<string, FunctionSymbol> _functions = new(StringComparer.Ordinal);
    private readonly Dictionary<string, RecordSymbol> _records = new(StringComparer.Ordinal);

    public CSharpEmitter(SourceText source, DiagnosticBag diagnostics)
    {
        _source = source;
        _diagnostics = diagnostics;
    }

    public string Emit(CompilationUnitSyntax root)
    {
        RegisterDeclarations(root);

        _writer.WriteLine("// <auto-generated />");
        _writer.WriteLine("using System;");
        _writer.WriteLine("using System.Collections.Generic;");
        _writer.WriteLine("using Vela.Runtime;");
        _writer.WriteLine();
        _writer.WriteLine("namespace Vela.Generated;");
        _writer.WriteLine();

        foreach (var record in root.Members.OfType<RecordDeclarationSyntax>())
        {
            EmitRecord(record);
            _writer.WriteLine();
        }

        _writer.WriteLine("public static class Program");
        _writer.WriteLine("{");
        _writer.Indent();
        EmitEntryPoint(root);

        foreach (var function in root.Members.OfType<FunctionDeclarationSyntax>())
        {
            _writer.WriteLine();
            EmitFunction(function);
        }

        var topLevelStatements = root.Members.Where(static member => member is not FunctionDeclarationSyntax and not RecordDeclarationSyntax).ToArray();
        if (topLevelStatements.Length > 0)
        {
            _writer.WriteLine();
            EmitScript(topLevelStatements);
        }

        _writer.Unindent();
        _writer.WriteLine("}");
        _writer.WriteLine("#line default");
        return _writer.ToString();
    }

    private void RegisterDeclarations(CompilationUnitSyntax root)
    {
        foreach (var member in root.Members)
        {
            switch (member)
            {
                case FunctionDeclarationSyntax function:
                    AddDeclaration(_functions, function.Identifier.Text, new FunctionSymbol(function), function.Identifier.Span, "function");
                    break;
                case RecordDeclarationSyntax record:
                    AddDeclaration(_records, record.Identifier.Text, new RecordSymbol(record), record.Identifier.Span, "record");
                    break;
            }
        }
    }

    private void AddDeclaration<TSymbol>(Dictionary<string, TSymbol> symbols, string name, TSymbol symbol, TextSpan span, string kind)
    {
        if (!symbols.TryAdd(name, symbol))
        {
            Report("VEL3000", span, $"Duplicate {kind} declaration '{name}'.", "Rename one declaration so every symbol in this scope is unique.");
        }
    }

    private void EmitEntryPoint(CompilationUnitSyntax root)
    {
        _writer.WriteLine("public static int Main(string[] args)");
        _writer.WriteLine("{");
        _writer.Indent();

        if (_functions.TryGetValue("main", out var main))
        {
            if (main.Syntax.Parameters.Count != 0)
            {
                Report("VEL3006", main.Syntax.Identifier.Span, "The entry function 'main' cannot declare parameters.", "Declare 'fn main() -> Int:' without parameters.");
            }

            if (main.GenericNames.Length != 0)
            {
                Report("VEL3006", main.Syntax.Identifier.Span, "The entry function 'main' cannot declare generic parameters.", "Declare a non-generic 'fn main() -> Int:'.");
            }

            var returnType = ResolveType(main.Syntax.ReturnType, main.GenericNames, main.Syntax.Identifier.Span, defaultType: VelaType.WholeNumber);
            if (!returnType.IsSameAs(VelaType.WholeNumber))
            {
                Report("VEL3007", main.Syntax.Identifier.Span, "The entry function 'main' must return Int.", "Change the declaration to 'fn main() -> Int:'.");
            }

            _writer.WriteLine("return checked((int)main());");
        }
        else if (root.Members.Any(static member => member is not FunctionDeclarationSyntax and not RecordDeclarationSyntax))
        {
            _writer.WriteLine("return __script();");
        }
        else
        {
            _writer.WriteLine("return 0;");
        }

        _writer.Unindent();
        _writer.WriteLine("}");
    }

    private void EmitRecord(RecordDeclarationSyntax record)
    {
        var symbol = _records[record.Identifier.Text];
        var genericNames = symbol.GenericNames;
        var fields = record.Members.OfType<RecordFieldSyntax>().ToArray();

        foreach (var method in record.Members.OfType<RecordMethodSyntax>())
        {
            Report("VEL3010", method.Span, "Record methods are not available in this compiler version.", "Move the behavior to a generic function and pass the record as an argument.");
        }

        WriteLineDirective(record);
        var genericSuffix = FormatGenericParameterNames(genericNames);
        var parameters = string.Join(", ", fields.Select(field =>
            $"{CSharpType(ResolveType(field.Type, genericNames, field.Type.Span))} {EscapeIdentifier(field.Identifier.Text)}"));
        _writer.WriteLine($"public sealed record {EscapeIdentifier(record.Identifier.Text)}{genericSuffix}({parameters});");
    }

    private void EmitFunction(FunctionDeclarationSyntax function)
    {
        var symbol = _functions[function.Identifier.Text];
        var genericNames = symbol.GenericNames;
        ValidateGenericConstraints(function.GenericParameters);
        var returnType = ResolveType(function.ReturnType, genericNames, function.Identifier.Span, defaultType: VelaType.Unit);
        var parameters = new List<string>();
        var scope = new Scope(null);

        foreach (var parameter in function.Parameters)
        {
            var parameterType = ResolveType(parameter.Type, genericNames, parameter.Type.Span);
            AddVariable(scope, parameter.Identifier.Text, new VariableSymbol(parameterType, false), parameter.Identifier.Span);
            parameters.Add($"{CSharpType(parameterType)} {EscapeIdentifier(parameter.Identifier.Text)}");
        }

        WriteLineDirective(function);
        _writer.WriteLine($"private static {CSharpType(returnType)} {EscapeIdentifier(function.Identifier.Text)}{FormatGenericParameterNames(genericNames)}({string.Join(", ", parameters)})");
        _writer.WriteLine("{");
        _writer.Indent();
        var alwaysReturns = EmitBlock(function.Body, scope, returnType, isTailBlock: true);
        if (!alwaysReturns && !returnType.IsSameAs(VelaType.Unit))
        {
            Report("VEL3007", function.Identifier.Span, $"Function '{function.Identifier.Text}' does not return {returnType} on every path.", "Return a value explicitly or end every control-flow branch with an expression.");
            _writer.WriteLine($"return {DefaultValue(returnType)};");
        }
        else if (!alwaysReturns && returnType.IsSameAs(VelaType.Unit))
        {
            _writer.WriteLine("return;");
        }

        _writer.Unindent();
        _writer.WriteLine("}");
    }

    private void EmitScript(IReadOnlyList<StatementSyntax> statements)
    {
        _writer.WriteLine("private static int __script()");
        _writer.WriteLine("{");
        _writer.Indent();
        var scope = new Scope(null);
        _ = EmitStatements(statements, scope, VelaType.WholeNumber, tailReturnsValue: false);
        _writer.WriteLine("return 0;");
        _writer.Unindent();
        _writer.WriteLine("}");
    }

    private bool EmitBlock(BlockSyntax block, Scope parent, VelaType returnType, bool isTailBlock)
    {
        var scope = new Scope(parent);
        return EmitStatements(block.Statements, scope, returnType, isTailBlock);
    }

    private bool EmitStatements(IReadOnlyList<StatementSyntax> statements, Scope scope, VelaType returnType, bool tailReturnsValue)
    {
        for (var index = 0; index < statements.Count; index++)
        {
            var isTail = tailReturnsValue && index == statements.Count - 1;
            var returns = EmitStatement(statements[index], scope, returnType, isTail);
            if (returns && index < statements.Count - 1)
            {
                Report("VEL3011", statements[index + 1].Span, "Unreachable statement after a return.", "Remove the statement or move it before the return.");
            }

            if (isTail)
            {
                return returns;
            }
        }

        return false;
    }

    private bool EmitStatement(StatementSyntax statement, Scope scope, VelaType returnType, bool isTail)
    {
        WriteLineDirective(statement);
        switch (statement)
        {
            case LetStatementSyntax let:
                EmitVariable(let.Identifier.Text, let.Type, let.Initializer, false, scope, let.Span);
                return false;
            case VarStatementSyntax variable:
                EmitVariable(variable.Identifier.Text, variable.Type, variable.Initializer, true, scope, variable.Span);
                return false;
            case ReturnStatementSyntax returnStatement:
                EmitReturn(returnStatement, scope, returnType);
                return true;
            case AssertStatementSyntax assertion:
                EmitAssert(assertion, scope);
                return false;
            case ExpressionStatementSyntax expressionStatement:
                return EmitExpressionStatement(expressionStatement.Expression, scope, returnType, isTail);
            case IfStatementSyntax conditional:
                return EmitIf(conditional, scope, returnType, isTail);
            case ForStatementSyntax loop:
                EmitFor(loop, scope, returnType);
                return false;
            case FunctionDeclarationSyntax:
            case RecordDeclarationSyntax:
                Report("VEL3012", statement.Span, "Declarations are only allowed at the top level.", "Move this declaration outside the current function or block.");
                return false;
            default:
                Report("VEL3013", statement.Span, "Unsupported statement.");
                return false;
        }
    }

    private void EmitVariable(string name, TypeSyntax? declaredTypeSyntax, ExpressionSyntax initializer, bool mutable, Scope scope, TextSpan span)
    {
        var initializerResult = EmitExpression(initializer, scope);
        var declaredType = declaredTypeSyntax is null
            ? initializerResult.Type
            : ResolveType(declaredTypeSyntax, EmptyGenericNames, declaredTypeSyntax.Span);
        EnsureAssignable(declaredType, initializerResult.Type, initializer.Span);
        AddVariable(scope, name, new VariableSymbol(declaredType, mutable), span);
        _writer.WriteLine($"{CSharpType(declaredType)} {EscapeIdentifier(name)} = {initializerResult.Code};");
    }

    private void EmitReturn(ReturnStatementSyntax statement, Scope scope, VelaType returnType)
    {
        if (statement.Expression is null)
        {
            if (!returnType.IsSameAs(VelaType.Unit))
            {
                Report("VEL3007", statement.ReturnKeyword.Span, $"A function returning {returnType} requires a value.", "Return an expression with the declared return type.");
            }

            _writer.WriteLine("return;");
            return;
        }

        var expression = EmitExpression(statement.Expression, scope);
        EnsureAssignable(returnType, expression.Type, statement.Expression.Span);
        _writer.WriteLine($"return {expression.Code};");
    }

    private void EmitAssert(AssertStatementSyntax assertion, Scope scope)
    {
        var condition = EmitExpression(assertion.Condition, scope);
        EnsureAssignable(VelaType.Bool, condition.Type, assertion.Condition.Span);
        var messageCode = QuoteString("Vela assertion failed.");
        if (assertion.Message is not null)
        {
            var messageExpression = EmitExpression(assertion.Message, scope);
            EnsureAssignable(VelaType.Text, messageExpression.Type, assertion.Message.Span);
            messageCode = messageExpression.Code;
        }

        _writer.WriteLine($"Contract.Require({condition.Code}, {messageCode});");
    }

    private bool EmitExpressionStatement(ExpressionSyntax expression, Scope scope, VelaType returnType, bool isTail)
    {
        var result = EmitExpression(expression, scope);
        if (isTail && !returnType.IsSameAs(VelaType.Unit))
        {
            EnsureAssignable(returnType, result.Type, expression.Span);
            _writer.WriteLine($"return {result.Code};");
            return true;
        }

        _writer.WriteLine($"{result.Code};");
        return false;
    }

    private bool EmitIf(IfStatementSyntax conditional, Scope scope, VelaType returnType, bool isTail)
    {
        var condition = EmitExpression(conditional.Condition, scope);
        EnsureAssignable(VelaType.Bool, condition.Type, conditional.Condition.Span);
        _writer.WriteLine($"if ({condition.Code})");
        _writer.WriteLine("{");
        _writer.Indent();
        var thenReturns = EmitBlock(conditional.ThenBlock, scope, returnType, isTail);
        _writer.Unindent();
        _writer.WriteLine("}");

        if (conditional.ElseClause is null)
        {
            return false;
        }

        _writer.WriteLine("else");
        _writer.WriteLine("{");
        _writer.Indent();
        var elseReturns = EmitBlock(conditional.ElseClause.Block, scope, returnType, isTail);
        _writer.Unindent();
        _writer.WriteLine("}");
        return isTail && thenReturns && elseReturns;
    }

    private void EmitFor(ForStatementSyntax loop, Scope scope, VelaType returnType)
    {
        var collection = EmitExpression(loop.Collection, scope);
        var elementType = GetIterationElementType(collection.Type, loop.Collection.Span);
        var loopScope = new Scope(scope);
        AddVariable(loopScope, loop.Identifier.Text, new VariableSymbol(elementType, false), loop.Identifier.Span);

        _writer.WriteLine($"foreach (var {EscapeIdentifier(loop.Identifier.Text)} in {collection.Code})");
        _writer.WriteLine("{");
        _writer.Indent();
        _ = EmitBlock(loop.Body, loopScope, returnType, isTailBlock: false);
        _writer.Unindent();
        _writer.WriteLine("}");
    }

    private ExpressionResult EmitExpression(ExpressionSyntax expression, Scope scope)
    {
        return expression switch
        {
            LiteralExpressionSyntax literal => EmitLiteral(literal),
            NameExpressionSyntax name => EmitName(name, scope),
            MemberAccessExpressionSyntax member => EmitMember(member, scope),
            IndexExpressionSyntax index => EmitIndex(index, scope),
            UnaryExpressionSyntax unary => EmitUnary(unary, scope),
            BinaryExpressionSyntax binary => EmitBinary(binary, scope),
            AssignmentExpressionSyntax assignment => EmitAssignment(assignment, scope),
            ParenthesizedExpressionSyntax parenthesized => EmitParenthesized(parenthesized, scope),
            CallExpressionSyntax call => EmitCall(call, scope),
            ListExpressionSyntax list => EmitList(list, scope),
            _ => UnsupportedExpression(expression)
        };
    }

    private ExpressionResult EmitLiteral(LiteralExpressionSyntax literal)
    {
        var token = literal.LiteralToken;
        return token.Kind switch
        {
            TokenKind.IntegerLiteral => new ExpressionResult(VelaType.WholeNumber, $"{token.Text}L"),
            TokenKind.FloatLiteral => new ExpressionResult(VelaType.FloatingPoint, $"{token.Text}d"),
            TokenKind.StringLiteral => new ExpressionResult(VelaType.Text, QuoteString((string?)token.Value ?? string.Empty)),
            TokenKind.TrueKeyword => new ExpressionResult(VelaType.Bool, "true"),
            TokenKind.FalseKeyword => new ExpressionResult(VelaType.Bool, "false"),
            TokenKind.NilKeyword => new ExpressionResult(VelaType.Nil, "null"),
            _ => UnsupportedExpression(literal)
        };
    }

    private ExpressionResult EmitName(NameExpressionSyntax name, Scope scope)
    {
        if (scope.TryLookup(name.Identifier.Text, out var variable))
        {
            return new ExpressionResult(variable.Type, EscapeIdentifier(name.Identifier.Text));
        }

        if (_functions.ContainsKey(name.Identifier.Text) || _records.ContainsKey(name.Identifier.Text))
        {
            return new ExpressionResult(VelaType.Unknown, EscapeIdentifier(name.Identifier.Text));
        }

        Report("VEL3001", name.Span, $"Unknown name '{name.Identifier.Text}'.", "Declare the name before using it or correct the spelling.");
        return new ExpressionResult(VelaType.Unknown, EscapeIdentifier(name.Identifier.Text));
    }

    private ExpressionResult EmitMember(MemberAccessExpressionSyntax member, Scope scope)
    {
        var receiver = EmitExpression(member.Receiver, scope);
        if (_records.TryGetValue(receiver.Type.Name, out var record))
        {
            var field = record.Syntax.Members.OfType<RecordFieldSyntax>().FirstOrDefault(candidate => candidate.Identifier.Text == member.Member.Text);
            if (field is not null)
            {
                var substitutions = CreateGenericSubstitutions(record.GenericNames, receiver.Type.TypeArguments.ToArray());
                var fieldType = ResolveType(field.Type, record.GenericNames, field.Type.Span).Substitute(substitutions);
                return new ExpressionResult(fieldType, $"{receiver.Code}.{EscapeIdentifier(member.Member.Text)}");
            }
        }

        if (receiver.Type.IsOptional && receiver.Type.TypeArguments.Count == 1)
        {
            return member.Member.Text switch
            {
                "has_value" => new ExpressionResult(VelaType.Bool, $"{receiver.Code}.HasValue"),
                "value" => new ExpressionResult(receiver.Type.TypeArguments[0], $"{receiver.Code}.Value"),
                _ => ReportUnknownOptionalMember(member, receiver)
            };
        }

        if (member.Member.Text == "count" && HasCountProperty(receiver.Type))
        {
            return new ExpressionResult(VelaType.WholeNumber, $"{receiver.Code}.Count");
        }

        if (member.Member.Text == "capacity" && HasCapacityProperty(receiver.Type))
        {
            return new ExpressionResult(VelaType.WholeNumber, $"{receiver.Code}.Capacity");
        }

        Report("VEL3009", member.Member.Span, $"Type '{receiver.Type}' does not contain member '{member.Member.Text}'.", "Use a declared record field or correct the member name.");
        return new ExpressionResult(VelaType.Unknown, $"{receiver.Code}.{EscapeIdentifier(member.Member.Text)}");
    }

    private ExpressionResult ReportUnknownOptionalMember(MemberAccessExpressionSyntax member, ExpressionResult receiver)
    {
        Report("VEL3009", member.Member.Span, $"Option does not contain member '{member.Member.Text}'.", "Use 'has_value' to test the option or 'value' to read the contained value.");
        return new ExpressionResult(VelaType.Unknown, $"{receiver.Code}.{EscapeIdentifier(member.Member.Text)}");
    }

    private ExpressionResult EmitIndex(IndexExpressionSyntax index, Scope scope)
    {
        var receiver = EmitExpression(index.Receiver, scope);
        var indexValue = EmitExpression(index.Index, scope);
        return receiver.Type.Name switch
        {
            "List" => EmitVectorIndex(index, receiver, indexValue),
            "HashMap" => EmitHashMapIndex(index, receiver, indexValue),
            _ => ReportUnsupportedIndex(index, receiver, indexValue)
        };
    }

    private ExpressionResult EmitVectorIndex(IndexExpressionSyntax index, ExpressionResult receiver, ExpressionResult indexValue)
    {
        EnsureAssignable(VelaType.WholeNumber, indexValue.Type, index.Index.Span);
        var elementType = receiver.Type.TypeArguments.Count == 1 ? receiver.Type.TypeArguments[0] : VelaType.Unknown;
        return new ExpressionResult(elementType, $"{receiver.Code}[checked((int){indexValue.Code})]");
    }

    private ExpressionResult EmitHashMapIndex(IndexExpressionSyntax index, ExpressionResult receiver, ExpressionResult indexValue)
    {
        if (receiver.Type.TypeArguments.Count != 2)
        {
            return new ExpressionResult(VelaType.Unknown, $"{receiver.Code}[{indexValue.Code}]");
        }

        var keyType = receiver.Type.TypeArguments[0];
        EnsureAssignable(keyType, indexValue.Type, index.Index.Span);
        EnsureHashable(keyType, index.Index.Span);
        return new ExpressionResult(receiver.Type.TypeArguments[1], $"{receiver.Code}[{indexValue.Code}]");
    }

    private ExpressionResult ReportUnsupportedIndex(IndexExpressionSyntax index, ExpressionResult receiver, ExpressionResult indexValue)
    {
        Report("VEL3009", index.Span, $"Type '{receiver.Type}' does not support indexing.", "Use Vector or HashMap indexing, or call a supported collection method.");
        return new ExpressionResult(VelaType.Unknown, $"{receiver.Code}[{indexValue.Code}]");
    }

    private ExpressionResult EmitUnary(UnaryExpressionSyntax unary, Scope scope)
    {
        var operand = EmitExpression(unary.Operand, scope);
        if (unary.OperatorToken.Kind == TokenKind.Minus && operand.Type.IsNumeric)
        {
            return new ExpressionResult(operand.Type, $"-{operand.Code}");
        }

        Report("VEL3002", unary.Span, $"Operator '{unary.OperatorToken.Text}' cannot be applied to {operand.Type}.");
        return new ExpressionResult(VelaType.Unknown, $"{unary.OperatorToken.Text}{operand.Code}");
    }

    private ExpressionResult EmitBinary(BinaryExpressionSyntax binary, Scope scope)
    {
        var left = EmitExpression(binary.Left, scope);
        var right = EmitExpression(binary.Right, scope);
        var operation = binary.OperatorToken.Kind;

        if (operation is TokenKind.EqualsEquals or TokenKind.BangEquals)
        {
            EnsureComparable(left.Type, right.Type, binary.Span);
            return new ExpressionResult(VelaType.Bool, $"{left.Code} {binary.OperatorToken.Text} {right.Code}");
        }

        if (operation is TokenKind.Less or TokenKind.LessOrEqual or TokenKind.Greater or TokenKind.GreaterOrEqual)
        {
            if (!left.Type.IsNumeric || !right.Type.IsNumeric)
            {
                Report("VEL3002", binary.Span, $"Operator '{binary.OperatorToken.Text}' requires numeric operands.");
            }

            return new ExpressionResult(VelaType.Bool, $"{left.Code} {binary.OperatorToken.Text} {right.Code}");
        }

        if (operation == TokenKind.Plus && left.Type.IsSameAs(VelaType.Text) && right.Type.IsSameAs(VelaType.Text))
        {
            return new ExpressionResult(VelaType.Text, $"{left.Code} + {right.Code}");
        }

        if (left.Type.IsNumeric && right.Type.IsNumeric)
        {
            var type = left.Type.IsSameAs(VelaType.FloatingPoint) || right.Type.IsSameAs(VelaType.FloatingPoint) ? VelaType.FloatingPoint : VelaType.WholeNumber;
            return new ExpressionResult(type, $"{left.Code} {binary.OperatorToken.Text} {right.Code}");
        }

        Report("VEL3002", binary.Span, $"Operator '{binary.OperatorToken.Text}' cannot be applied to {left.Type} and {right.Type}.");
        return new ExpressionResult(VelaType.Unknown, $"{left.Code} {binary.OperatorToken.Text} {right.Code}");
    }

    private ExpressionResult EmitAssignment(AssignmentExpressionSyntax assignment, Scope scope)
    {
        if (assignment.Target is IndexExpressionSyntax index)
        {
            return EmitIndexedAssignment(index, assignment.Value, scope);
        }

        if (assignment.Target is not NameExpressionSyntax target)
        {
            Report("VEL3004", assignment.Target.Span, "Only named mutable bindings can be assigned.", "Assign to a variable declared with 'var'.");
            return new ExpressionResult(VelaType.Unknown, "default");
        }

        var value = EmitExpression(assignment.Value, scope);
        if (!scope.TryLookup(target.Identifier.Text, out var variable))
        {
            Report("VEL3001", target.Span, $"Unknown name '{target.Identifier.Text}'.", "Declare the variable before assigning to it.");
            return new ExpressionResult(VelaType.Unknown, $"{EscapeIdentifier(target.Identifier.Text)} = {value.Code}");
        }

        if (!variable.Mutable)
        {
            Report("VEL3004", target.Span, $"Cannot assign to immutable binding '{target.Identifier.Text}'.", "Declare the binding with 'var' if it must change.");
        }

        EnsureAssignable(variable.Type, value.Type, assignment.Value.Span);
        return new ExpressionResult(variable.Type, $"{EscapeIdentifier(target.Identifier.Text)} = {value.Code}");
    }

    private ExpressionResult EmitIndexedAssignment(IndexExpressionSyntax index, ExpressionSyntax valueSyntax, Scope scope)
    {
        var receiver = EmitExpression(index.Receiver, scope);
        var indexValue = EmitExpression(index.Index, scope);
        var value = EmitExpression(valueSyntax, scope);
        switch (receiver.Type.Name)
        {
            case "List" when receiver.Type.TypeArguments.Count == 1:
                EnsureAssignable(VelaType.WholeNumber, indexValue.Type, index.Index.Span);
                EnsureAssignable(receiver.Type.TypeArguments[0], value.Type, valueSyntax.Span);
                return new ExpressionResult(receiver.Type.TypeArguments[0], $"{receiver.Code}[checked((int){indexValue.Code})] = {value.Code}");
            case "HashMap" when receiver.Type.TypeArguments.Count == 2:
                EnsureAssignable(receiver.Type.TypeArguments[0], indexValue.Type, index.Index.Span);
                EnsureHashable(receiver.Type.TypeArguments[0], index.Index.Span);
                EnsureAssignable(receiver.Type.TypeArguments[1], value.Type, valueSyntax.Span);
                return new ExpressionResult(receiver.Type.TypeArguments[1], $"{receiver.Code}[{indexValue.Code}] = {value.Code}");
            default:
                Report("VEL3009", index.Span, $"Type '{receiver.Type}' does not support indexed assignment.", "Use Vector or HashMap indexing, or call a supported collection method.");
                return new ExpressionResult(VelaType.Unknown, "default");
        }
    }

    private ExpressionResult EmitParenthesized(ParenthesizedExpressionSyntax expression, Scope scope)
    {
        var inner = EmitExpression(expression.Expression, scope);
        return new ExpressionResult(inner.Type, $"({inner.Code})");
    }

    private ExpressionResult EmitCall(CallExpressionSyntax call, Scope scope)
    {
        if (call.Callee is MemberAccessExpressionSyntax member)
        {
            return EmitCollectionMethodCall(call, member, scope);
        }

        if (call.Callee is not NameExpressionSyntax name)
        {
            Report("VEL3005", call.Callee.Span, "Only named functions, records, and collection methods can be called.");
            return new ExpressionResult(VelaType.Unknown, "default");
        }

        var arguments = call.Arguments.Select(argument => EmitExpression(argument, scope)).ToArray();
        var explicitTypes = call.TypeArguments.Select(type => ResolveType(type, EmptyGenericNames, type.Span)).ToArray();
        if (name.Identifier.Text == "print")
        {
            if (arguments.Length != 1)
            {
                Report("VEL3006", call.Span, "Function 'print' expects exactly one argument.");
            }

            var printedValue = arguments.Length == 0 ? "string.Empty" : arguments[0].Code;
            return new ExpressionResult(VelaType.Unit, $"Console.WriteLine({printedValue})");
        }

        if (IsCollectionConstructor(name.Identifier.Text))
        {
            return EmitCollectionConstruction(call, name.Identifier.Text, arguments, explicitTypes);
        }

        if (_functions.TryGetValue(name.Identifier.Text, out var function))
        {
            return EmitFunctionCall(call, function, arguments, explicitTypes);
        }

        if (_records.TryGetValue(name.Identifier.Text, out var record))
        {
            return EmitRecordConstruction(call, record, arguments, explicitTypes);
        }

        Report("VEL3005", name.Span, $"Unknown function or record '{name.Identifier.Text}'.", "Declare it before calling it or correct the spelling.");
        return new ExpressionResult(VelaType.Unknown, $"{EscapeIdentifier(name.Identifier.Text)}({string.Join(", ", arguments.Select(static argument => argument.Code))})");
    }

    private ExpressionResult EmitCollectionMethodCall(CallExpressionSyntax call, MemberAccessExpressionSyntax member, Scope scope)
    {
        if (call.TypeArguments.Count != 0)
        {
            Report("VEL3006", call.Span, "Collection methods do not accept explicit type arguments.");
        }

        var receiver = EmitExpression(member.Receiver, scope);
        var arguments = call.Arguments.Select(argument => EmitExpression(argument, scope)).ToArray();
        return receiver.Type.Name switch
        {
            "List" when receiver.Type.TypeArguments.Count == 1 => EmitVectorMethod(call, receiver, member.Member, arguments),
            "HashMap" when receiver.Type.TypeArguments.Count == 2 => EmitHashMapMethod(call, receiver, member.Member, arguments),
            "HashSet" when receiver.Type.TypeArguments.Count == 1 => EmitHashSetMethod(call, receiver, member.Member, arguments),
            "Queue" when receiver.Type.TypeArguments.Count == 1 => EmitQueueMethod(call, receiver, member.Member, arguments),
            "Stack" when receiver.Type.TypeArguments.Count == 1 => EmitStackMethod(call, receiver, member.Member, arguments),
            "RingBuffer" when receiver.Type.TypeArguments.Count == 1 => EmitRingBufferMethod(call, receiver, member.Member, arguments),
            "BitSet" => EmitBitSetMethod(call, receiver, member.Member, arguments),
            _ => ReportUnsupportedCollectionMethod(call, receiver, member.Member, arguments)
        };
    }

    private ExpressionResult EmitVectorMethod(CallExpressionSyntax call, ExpressionResult receiver, SyntaxToken member, ExpressionResult[] arguments)
    {
        var element = receiver.Type.TypeArguments[0];
        return member.Text switch
        {
            "append" => EmitCollectionOperation(call, receiver, member, "Append", VelaType.Unit, arguments, [element]),
            "pop" => EmitCollectionOperation(call, receiver, member, "Pop", new VelaType("Option", [element]), arguments, []),
            "reserve" => EmitCollectionOperation(call, receiver, member, "Reserve", VelaType.Unit, arguments, [VelaType.WholeNumber]),
            "clear" => EmitCollectionOperation(call, receiver, member, "Clear", VelaType.Unit, arguments, []),
            _ => ReportUnsupportedCollectionMethod(call, receiver, member, arguments)
        };
    }

    private ExpressionResult EmitHashMapMethod(CallExpressionSyntax call, ExpressionResult receiver, SyntaxToken member, ExpressionResult[] arguments)
    {
        var key = receiver.Type.TypeArguments[0];
        var value = receiver.Type.TypeArguments[1];
        EnsureHashable(key, member.Span);
        return member.Text switch
        {
            "set" => EmitCollectionOperation(call, receiver, member, "Set", VelaType.Unit, arguments, [key, value]),
            "try_get" => EmitCollectionOperation(call, receiver, member, "TryGet", new VelaType("Option", [value]), arguments, [key]),
            "contains" => EmitCollectionOperation(call, receiver, member, "Contains", VelaType.Bool, arguments, [key]),
            "remove" => EmitCollectionOperation(call, receiver, member, "Remove", VelaType.Bool, arguments, [key]),
            "reserve" => EmitCollectionOperation(call, receiver, member, "Reserve", VelaType.Unit, arguments, [VelaType.WholeNumber]),
            "clear" => EmitCollectionOperation(call, receiver, member, "Clear", VelaType.Unit, arguments, []),
            _ => ReportUnsupportedCollectionMethod(call, receiver, member, arguments)
        };
    }

    private ExpressionResult EmitHashSetMethod(CallExpressionSyntax call, ExpressionResult receiver, SyntaxToken member, ExpressionResult[] arguments)
    {
        var element = receiver.Type.TypeArguments[0];
        EnsureHashable(element, member.Span);
        return member.Text switch
        {
            "add" => EmitCollectionOperation(call, receiver, member, "Add", VelaType.Bool, arguments, [element]),
            "contains" => EmitCollectionOperation(call, receiver, member, "Contains", VelaType.Bool, arguments, [element]),
            "remove" => EmitCollectionOperation(call, receiver, member, "Remove", VelaType.Bool, arguments, [element]),
            "reserve" => EmitCollectionOperation(call, receiver, member, "Reserve", VelaType.Unit, arguments, [VelaType.WholeNumber]),
            "clear" => EmitCollectionOperation(call, receiver, member, "Clear", VelaType.Unit, arguments, []),
            _ => ReportUnsupportedCollectionMethod(call, receiver, member, arguments)
        };
    }

    private ExpressionResult EmitQueueMethod(CallExpressionSyntax call, ExpressionResult receiver, SyntaxToken member, ExpressionResult[] arguments)
    {
        var element = receiver.Type.TypeArguments[0];
        return member.Text switch
        {
            "enqueue" => EmitCollectionOperation(call, receiver, member, "Enqueue", VelaType.Unit, arguments, [element]),
            "dequeue" => EmitCollectionOperation(call, receiver, member, "Dequeue", new VelaType("Option", [element]), arguments, []),
            "peek" => EmitCollectionOperation(call, receiver, member, "Peek", new VelaType("Option", [element]), arguments, []),
            "reserve" => EmitCollectionOperation(call, receiver, member, "Reserve", VelaType.Unit, arguments, [VelaType.WholeNumber]),
            "clear" => EmitCollectionOperation(call, receiver, member, "Clear", VelaType.Unit, arguments, []),
            _ => ReportUnsupportedCollectionMethod(call, receiver, member, arguments)
        };
    }

    private ExpressionResult EmitStackMethod(CallExpressionSyntax call, ExpressionResult receiver, SyntaxToken member, ExpressionResult[] arguments)
    {
        var element = receiver.Type.TypeArguments[0];
        return member.Text switch
        {
            "push" => EmitCollectionOperation(call, receiver, member, "Push", VelaType.Unit, arguments, [element]),
            "pop" => EmitCollectionOperation(call, receiver, member, "Pop", new VelaType("Option", [element]), arguments, []),
            "peek" => EmitCollectionOperation(call, receiver, member, "Peek", new VelaType("Option", [element]), arguments, []),
            "clear" => EmitCollectionOperation(call, receiver, member, "Clear", VelaType.Unit, arguments, []),
            _ => ReportUnsupportedCollectionMethod(call, receiver, member, arguments)
        };
    }

    private ExpressionResult EmitRingBufferMethod(CallExpressionSyntax call, ExpressionResult receiver, SyntaxToken member, ExpressionResult[] arguments)
    {
        var element = receiver.Type.TypeArguments[0];
        return member.Text switch
        {
            "try_enqueue" => EmitCollectionOperation(call, receiver, member, "TryEnqueue", VelaType.Bool, arguments, [element]),
            "dequeue" => EmitCollectionOperation(call, receiver, member, "Dequeue", new VelaType("Option", [element]), arguments, []),
            "peek" => EmitCollectionOperation(call, receiver, member, "Peek", new VelaType("Option", [element]), arguments, []),
            "clear" => EmitCollectionOperation(call, receiver, member, "Clear", VelaType.Unit, arguments, []),
            _ => ReportUnsupportedCollectionMethod(call, receiver, member, arguments)
        };
    }

    private ExpressionResult EmitBitSetMethod(CallExpressionSyntax call, ExpressionResult receiver, SyntaxToken member, ExpressionResult[] arguments)
    {
        return member.Text switch
        {
            "set" => EmitBitSetOperation(call, receiver, member, "Set", VelaType.Unit, arguments, expectsIndex: true),
            "clear" when arguments.Length == 0 => EmitCollectionOperation(call, receiver, member, "Clear", VelaType.Unit, arguments, []),
            "clear" => EmitBitSetOperation(call, receiver, member, "Clear", VelaType.Unit, arguments, expectsIndex: true),
            "contains" => EmitBitSetOperation(call, receiver, member, "Contains", VelaType.Bool, arguments, expectsIndex: true),
            "reserve" => EmitBitSetOperation(call, receiver, member, "Reserve", VelaType.Unit, arguments, expectsIndex: false),
            _ => ReportUnsupportedCollectionMethod(call, receiver, member, arguments)
        };
    }

    private ExpressionResult EmitBitSetOperation(
        CallExpressionSyntax call,
        ExpressionResult receiver,
        SyntaxToken member,
        string runtimeMember,
        VelaType returnType,
        ExpressionResult[] arguments,
        bool expectsIndex)
    {
        if (arguments.Length != 1)
        {
            var kind = expectsIndex ? "index" : "capacity";
            Report("VEL3006", call.Span, $"Method '{member.Text}' expects exactly one Int {kind} argument.");
        }

        if (arguments.Length > 0)
        {
            EnsureAssignable(VelaType.WholeNumber, arguments[0].Type, call.Arguments[0].Span);
        }

        var argumentCode = arguments.Length == 0 ? "0" : $"checked((int){arguments[0].Code})";
        return new ExpressionResult(returnType, $"{receiver.Code}.{runtimeMember}({argumentCode})");
    }

    private ExpressionResult EmitCollectionOperation(
        CallExpressionSyntax call,
        ExpressionResult receiver,
        SyntaxToken member,
        string runtimeMember,
        VelaType returnType,
        ExpressionResult[] arguments,
        IReadOnlyList<VelaType> parameterTypes)
    {
        if (arguments.Length != parameterTypes.Count)
        {
            Report("VEL3006", call.Span, $"Method '{member.Text}' expects {parameterTypes.Count} argument(s), but received {arguments.Length}.");
        }

        for (var index = 0; index < Math.Min(arguments.Length, parameterTypes.Count); index++)
        {
            EnsureAssignable(parameterTypes[index], arguments[index].Type, call.Arguments[index].Span);
        }

        return new ExpressionResult(returnType, $"{receiver.Code}.{runtimeMember}({string.Join(", ", arguments.Select(static argument => argument.Code))})");
    }

    private ExpressionResult ReportUnsupportedCollectionMethod(CallExpressionSyntax call, ExpressionResult receiver, SyntaxToken member, ExpressionResult[] arguments)
    {
        Report("VEL3009", member.Span, $"Type '{receiver.Type}' does not contain method '{member.Text}'.", "Use a supported collection operation or correct the method name.");
        return new ExpressionResult(VelaType.Unknown, $"{receiver.Code}.{EscapeIdentifier(member.Text)}({string.Join(", ", arguments.Select(static argument => argument.Code))})");
    }

    private ExpressionResult EmitCollectionConstruction(CallExpressionSyntax call, string name, ExpressionResult[] arguments, VelaType[] explicitTypes)
    {
        return name switch
        {
            "List" or "Vector" => EmitGenericCollectionConstruction(call, name, "VelaVector", "List", 1, arguments, explicitTypes, capacityRequired: false),
            "HashMap" => EmitGenericCollectionConstruction(call, name, "VelaHashMap", "HashMap", 2, arguments, explicitTypes, capacityRequired: false),
            "HashSet" => EmitGenericCollectionConstruction(call, name, "VelaHashSet", "HashSet", 1, arguments, explicitTypes, capacityRequired: false),
            "Queue" => EmitGenericCollectionConstruction(call, name, "VelaQueue", "Queue", 1, arguments, explicitTypes, capacityRequired: false),
            "Stack" => EmitGenericCollectionConstruction(call, name, "VelaStack", "Stack", 1, arguments, explicitTypes, capacityRequired: false),
            "RingBuffer" => EmitGenericCollectionConstruction(call, name, "RingBuffer", "RingBuffer", 1, arguments, explicitTypes, capacityRequired: true),
            "BitSet" => EmitBitSetConstruction(call, arguments, explicitTypes),
            _ => throw new InvalidOperationException($"Unsupported collection constructor '{name}'.")
        };
    }

    private ExpressionResult EmitGenericCollectionConstruction(
        CallExpressionSyntax call,
        string sourceName,
        string runtimeName,
        string canonicalName,
        int expectedTypeArgumentCount,
        ExpressionResult[] arguments,
        VelaType[] explicitTypes,
        bool capacityRequired)
    {
        var typeArguments = ValidateCollectionTypeArguments(call, sourceName, explicitTypes, expectedTypeArgumentCount);
        if (canonicalName is "HashMap" or "HashSet")
        {
            EnsureHashable(typeArguments[0], call.Span);
        }

        ValidateCapacityConstructorArguments(call, sourceName, arguments, capacityRequired);
        var capacity = arguments.Length == 0 ? string.Empty : $"checked((int){arguments[0].Code})";
        var genericSuffix = $"<{string.Join(", ", typeArguments.Select(CSharpType))}>";
        return new ExpressionResult(new VelaType(canonicalName, typeArguments), $"new {runtimeName}{genericSuffix}({capacity})");
    }

    private ExpressionResult EmitBitSetConstruction(CallExpressionSyntax call, ExpressionResult[] arguments, VelaType[] explicitTypes)
    {
        _ = ValidateCollectionTypeArguments(call, "BitSet", explicitTypes, 0);
        ValidateCapacityConstructorArguments(call, "BitSet", arguments, capacityRequired: true);
        var capacity = arguments.Length == 0 ? "0L" : arguments[0].Code;
        return new ExpressionResult(new VelaType("BitSet"), $"new BitSet(checked((int){capacity}))");
    }

    private VelaType[] ValidateCollectionTypeArguments(CallExpressionSyntax call, string name, VelaType[] explicitTypes, int expectedCount)
    {
        if (explicitTypes.Length != expectedCount)
        {
            Report("VEL3006", call.Span, $"Collection '{name}' expects {expectedCount} type argument(s), but received {explicitTypes.Length}.", "Supply explicit type arguments for the collection element or key and value types.");
        }

        return Enumerable.Range(0, expectedCount)
            .Select(index => index < explicitTypes.Length ? explicitTypes[index] : VelaType.Unknown)
            .ToArray();
    }

    private void ValidateCapacityConstructorArguments(CallExpressionSyntax call, string name, ExpressionResult[] arguments, bool capacityRequired)
    {
        var minimum = capacityRequired ? 1 : 0;
        if (arguments.Length < minimum || arguments.Length > 1)
        {
            var expected = capacityRequired ? "exactly one" : "zero or one";
            Report("VEL3006", call.Span, $"Collection '{name}' expects {expected} Int capacity argument.");
        }

        if (arguments.Length > 0)
        {
            EnsureAssignable(VelaType.WholeNumber, arguments[0].Type, call.Arguments[0].Span);
            if (TryGetIntegerConstant(call.Arguments[0], out var capacity))
            {
                if (capacity < 0)
                {
                    Report("VEL3006", call.Arguments[0].Span, $"Collection '{name}' capacity cannot be negative.", "Use zero or a positive Int capacity.");
                }
                else if (name == "RingBuffer" && capacity == 0)
                {
                    Report("VEL3006", call.Arguments[0].Span, "RingBuffer capacity must be positive.", "Use an Int capacity greater than zero.");
                }
            }
        }
    }

    private static bool TryGetIntegerConstant(ExpressionSyntax expression, out long value)
    {
        if (expression is LiteralExpressionSyntax { LiteralToken.Kind: TokenKind.IntegerLiteral, LiteralToken.Value: long integer })
        {
            value = integer;
            return true;
        }

        if (expression is UnaryExpressionSyntax
            {
                OperatorToken.Kind: TokenKind.Minus,
                Operand: LiteralExpressionSyntax { LiteralToken.Kind: TokenKind.IntegerLiteral, LiteralToken.Value: long negativeInteger }
            })
        {
            value = -negativeInteger;
            return true;
        }

        value = default;
        return false;
    }

    private ExpressionResult EmitFunctionCall(CallExpressionSyntax call, FunctionSymbol function, ExpressionResult[] arguments, VelaType[] explicitTypes)
    {
        if (arguments.Length != function.Syntax.Parameters.Count)
        {
            Report("VEL3006", call.Span, $"Function '{function.Syntax.Identifier.Text}' expects {function.Syntax.Parameters.Count} argument(s), but received {arguments.Length}.");
        }

        var substitutions = CreateGenericSubstitutions(function.GenericNames, explicitTypes);
        if (explicitTypes.Length > 0 && explicitTypes.Length != function.GenericNames.Length)
        {
            Report("VEL3006", call.Span, $"Function '{function.Syntax.Identifier.Text}' expects {function.GenericNames.Length} type argument(s), but received {explicitTypes.Length}.");
        }

        for (var index = 0; index < Math.Min(arguments.Length, function.Syntax.Parameters.Count); index++)
        {
            var expected = ResolveType(function.Syntax.Parameters[index].Type, function.GenericNames, function.Syntax.Parameters[index].Type.Span);
            InferGenericArguments(expected, arguments[index].Type, function.GenericNames, substitutions);
        }

        foreach (var genericName in function.GenericNames)
        {
            if (!substitutions.ContainsKey(genericName))
            {
                Report("VEL3006", call.Span, $"Cannot infer generic type parameter '{genericName}' for function '{function.Syntax.Identifier.Text}'.", "Supply an explicit type argument.");
                substitutions[genericName] = VelaType.Unknown;
            }
        }

        for (var index = 0; index < Math.Min(arguments.Length, function.Syntax.Parameters.Count); index++)
        {
            var expected = ResolveType(function.Syntax.Parameters[index].Type, function.GenericNames, function.Syntax.Parameters[index].Type.Span).Substitute(substitutions);
            EnsureAssignable(expected, arguments[index].Type, call.Arguments[index].Span);
        }

        var returnType = ResolveType(function.Syntax.ReturnType, function.GenericNames, function.Syntax.Identifier.Span, defaultType: VelaType.Unit).Substitute(substitutions);
        var typeArguments = explicitTypes.Length > 0
            ? $"<{string.Join(", ", explicitTypes.Select(CSharpType))}>"
            : string.Empty;
        var code = $"{EscapeIdentifier(function.Syntax.Identifier.Text)}{typeArguments}({string.Join(", ", arguments.Select(static argument => argument.Code))})";
        return new ExpressionResult(returnType, code);
    }

    private ExpressionResult EmitRecordConstruction(CallExpressionSyntax call, RecordSymbol record, ExpressionResult[] arguments, VelaType[] explicitTypes)
    {
        var fields = record.Syntax.Members.OfType<RecordFieldSyntax>().ToArray();
        if (arguments.Length != fields.Length)
        {
            Report("VEL3006", call.Span, $"Record '{record.Syntax.Identifier.Text}' expects {fields.Length} value(s), but received {arguments.Length}.");
        }

        var substitutions = CreateGenericSubstitutions(record.GenericNames, explicitTypes);
        for (var index = 0; index < Math.Min(arguments.Length, fields.Length); index++)
        {
            var expected = ResolveType(fields[index].Type, record.GenericNames, fields[index].Type.Span);
            InferGenericArguments(expected, arguments[index].Type, record.GenericNames, substitutions);
        }

        foreach (var genericName in record.GenericNames)
        {
            if (!substitutions.ContainsKey(genericName))
            {
                Report("VEL3006", call.Span, $"Cannot infer generic type parameter '{genericName}' for record '{record.Syntax.Identifier.Text}'.", "Supply an explicit type argument.");
                substitutions[genericName] = VelaType.Unknown;
            }
        }

        for (var index = 0; index < Math.Min(arguments.Length, fields.Length); index++)
        {
            var expected = ResolveType(fields[index].Type, record.GenericNames, fields[index].Type.Span).Substitute(substitutions);
            EnsureAssignable(expected, arguments[index].Type, call.Arguments[index].Span);
        }

        var constructedType = new VelaType(record.Syntax.Identifier.Text, record.GenericNames.Select(name => substitutions.TryGetValue(name, out var type) ? type : VelaType.Unknown).ToArray());
        var typeArguments = constructedType.TypeArguments.Count == 0 ? string.Empty : $"<{string.Join(", ", constructedType.TypeArguments.Select(CSharpType))}>";
        var code = $"new {EscapeIdentifier(record.Syntax.Identifier.Text)}{typeArguments}({string.Join(", ", arguments.Select(static argument => argument.Code))})";
        return new ExpressionResult(constructedType, code);
    }

    private ExpressionResult EmitList(ListExpressionSyntax list, Scope scope)
    {
        var elements = list.Elements.Select(element => EmitExpression(element, scope)).ToArray();
        var elementType = elements.Length == 0 ? VelaType.Unknown : elements[0].Type;
        foreach (var element in elements.Skip(1))
        {
            EnsureAssignable(elementType, element.Type, list.Span);
        }

        if (elementType.IsUnknown)
        {
            Report("VEL3006", list.Span, "Cannot infer the type of an empty list.", "Add at least one element or use an explicitly typed variable.");
        }

        return new ExpressionResult(
            new VelaType("List", [elementType]),
            $"new VelaVector<{CSharpType(elementType)}>(new {CSharpType(elementType)}[] {{ {string.Join(", ", elements.Select(static element => element.Code))} }})");
    }

    private ExpressionResult UnsupportedExpression(ExpressionSyntax expression)
    {
        Report("VEL3013", expression.Span, "Unsupported expression.");
        return new ExpressionResult(VelaType.Unknown, "default");
    }

    private VelaType ResolveType(TypeSyntax? syntax, IReadOnlyCollection<string> genericNames, TextSpan span, VelaType? defaultType = null)
    {
        if (syntax is null)
        {
            return defaultType ?? VelaType.Unknown;
        }

        if (syntax is not NamedTypeSyntax named)
        {
            Report("VEL3013", syntax.Span, "Unsupported type syntax.");
            return VelaType.Unknown;
        }

        var arguments = named.TypeArguments.Select(argument => ResolveType(argument, genericNames, argument.Span)).ToArray();
        var type = named.Identifier.Text switch
        {
            "Int" => VelaType.WholeNumber,
            "Float" => VelaType.FloatingPoint,
            "Bool" => VelaType.Bool,
            "Text" => VelaType.Text,
            "Unit" => VelaType.Unit,
            "List" or "Vector" => new VelaType("List", arguments),
            "Result" or "Option" or "HashMap" or "HashSet" or "Queue" or "Stack" or "RingBuffer" or "BitSet" => new VelaType(named.Identifier.Text, arguments),
            _ when genericNames.Contains(named.Identifier.Text) && arguments.Length == 0 => new VelaType(named.Identifier.Text),
            _ when _records.ContainsKey(named.Identifier.Text) => new VelaType(named.Identifier.Text, arguments),
            _ => ReportUnknownType(named)
        };

        ValidateTypeArgumentCount(type, named.Span, arguments.Length);
        if (named.QuestionToken is not null)
        {
            type = new VelaType("Option", [type]);
        }

        return type;
    }

    private VelaType ReportUnknownType(NamedTypeSyntax named)
    {
        Report("VEL3001", named.Span, $"Unknown type '{named.Identifier.Text}'.", "Use a built-in type, a generic parameter, or a declared record.");
        return VelaType.Unknown;
    }

    private void ValidateTypeArgumentCount(VelaType type, TextSpan span, int actualCount)
    {
        int expected = type.Name switch
        {
            "List" or "Option" or "HashSet" or "Queue" or "Stack" or "RingBuffer" => 1,
            "Result" or "HashMap" => 2,
            "BitSet" => 0,
            _ when _records.TryGetValue(type.Name, out var record) => record.GenericNames.Length,
            _ => 0
        };

        if (type.Name != "<unknown>" && actualCount != expected)
        {
            Report("VEL3006", span, $"Type '{type.Name}' expects {expected} type argument(s), but received {actualCount}.");
        }
    }

    private void ValidateGenericConstraints(IReadOnlyList<GenericParameterSyntax> parameters)
    {
        foreach (var parameter in parameters.Where(static parameter => parameter.Constraint is not null))
        {
            Report("VEL3010", parameter.Span, $"Generic constraint on '{parameter.Identifier.Text}' is not available in this compiler version.", "Remove the constraint or enforce it through a runtime contract.");
        }
    }

    private void InferGenericArguments(VelaType expected, VelaType actual, IReadOnlyCollection<string> genericNames, IDictionary<string, VelaType> substitutions)
    {
        if (genericNames.Contains(expected.Name) && expected.TypeArguments.Count == 0)
        {
            if (substitutions.TryGetValue(expected.Name, out var existing))
            {
                EnsureAssignable(existing, actual, default);
            }
            else
            {
                substitutions[expected.Name] = actual;
            }

            return;
        }

        if (expected.Name != actual.Name || expected.TypeArguments.Count != actual.TypeArguments.Count)
        {
            return;
        }

        for (var index = 0; index < expected.TypeArguments.Count; index++)
        {
            InferGenericArguments(expected.TypeArguments[index], actual.TypeArguments[index], genericNames, substitutions);
        }
    }

    private static Dictionary<string, VelaType> CreateGenericSubstitutions(string[] genericNames, VelaType[] explicitTypes)
    {
        var substitutions = new Dictionary<string, VelaType>(StringComparer.Ordinal);
        for (var index = 0; index < Math.Min(genericNames.Length, explicitTypes.Length); index++)
        {
            substitutions[genericNames[index]] = explicitTypes[index];
        }

        return substitutions;
    }

    private void EnsureAssignable(VelaType expected, VelaType actual, TextSpan span)
    {
        if (expected.IsUnknown || actual.IsUnknown || expected.IsSameAs(actual) || (expected.IsSameAs(VelaType.FloatingPoint) && actual.IsSameAs(VelaType.WholeNumber)) || (actual.IsSameAs(VelaType.Nil) && (expected.IsSameAs(VelaType.Text) || expected.IsOptional)))
        {
            return;
        }

        Report("VEL3002", span, $"Type mismatch: expected {expected}, found {actual}.", "Change the value or update the declared type.");
    }

    private void EnsureComparable(VelaType left, VelaType right, TextSpan span)
    {
        if (left.IsUnknown || right.IsUnknown || left.IsSameAs(right) || (left.IsNumeric && right.IsNumeric) || left.IsSameAs(VelaType.Nil) || right.IsSameAs(VelaType.Nil))
        {
            return;
        }

        Report("VEL3002", span, $"Values of type {left} and {right} cannot be compared.");
    }

    private void EnsureHashable(VelaType type, TextSpan span)
    {
        if (type.IsUnknown || type.Name is "Int" or "Float" or "Bool" or "Text" or "Option" or "Result" || _records.ContainsKey(type.Name))
        {
            return;
        }

        Report("VEL3006", span, $"Type '{type}' cannot be used as a hash key.", "Use a primitive value, an immutable record, Option, or Result as the key.");
    }

    private VelaType GetIterationElementType(VelaType collectionType, TextSpan span)
    {
        if (collectionType.Name is "List" or "HashSet" or "Queue" or "Stack" or "RingBuffer" && collectionType.TypeArguments.Count == 1)
        {
            return collectionType.TypeArguments[0];
        }

        Report("VEL3006", span, $"Type '{collectionType}' cannot be iterated.", "Use Vector, HashSet, Queue, Stack, or RingBuffer in a for loop.");
        return VelaType.Unknown;
    }

    private static bool HasCountProperty(VelaType type) => type.Name is "List" or "HashMap" or "HashSet" or "Queue" or "Stack" or "RingBuffer";

    private static bool HasCapacityProperty(VelaType type) => type.Name is "List" or "Queue" or "RingBuffer" or "BitSet";

    private static bool IsCollectionConstructor(string name) => name is "List" or "Vector" or "HashMap" or "HashSet" or "Queue" or "Stack" or "RingBuffer" or "BitSet";

    private void AddVariable(Scope scope, string name, VariableSymbol symbol, TextSpan span)
    {
        if (!scope.TryAdd(name, symbol))
        {
            Report("VEL3000", span, $"Duplicate local binding '{name}'.", "Use a distinct name in this scope.");
        }
    }

    private void WriteLineDirective(SyntaxNode syntax)
    {
        var location = _source.GetLocation(syntax.Span);
        var path = _source.FilePath.Replace("\\", "\\\\", StringComparison.Ordinal).Replace("\"", "\\\"", StringComparison.Ordinal);
        _writer.WriteLine($"#line {location.Line.ToString(CultureInfo.InvariantCulture)} \"{path}\"");
    }

    private static string CSharpType(VelaType type) => type.Name switch
    {
        "Int" => "long",
        "Float" => "double",
        "Bool" => "bool",
        "Text" => "string",
        "Unit" => "void",
        "Option" when type.TypeArguments.Count == 1 => $"Option<{CSharpType(type.TypeArguments[0])}>",
        "Result" when type.TypeArguments.Count == 2 => $"Result<{CSharpType(type.TypeArguments[0])}, {CSharpType(type.TypeArguments[1])}>",
        "List" when type.TypeArguments.Count == 1 => $"VelaVector<{CSharpType(type.TypeArguments[0])}>",
        "HashMap" when type.TypeArguments.Count == 2 => $"VelaHashMap<{CSharpType(type.TypeArguments[0])}, {CSharpType(type.TypeArguments[1])}>",
        "HashSet" when type.TypeArguments.Count == 1 => $"VelaHashSet<{CSharpType(type.TypeArguments[0])}>",
        "Queue" when type.TypeArguments.Count == 1 => $"VelaQueue<{CSharpType(type.TypeArguments[0])}>",
        "Stack" when type.TypeArguments.Count == 1 => $"VelaStack<{CSharpType(type.TypeArguments[0])}>",
        "RingBuffer" when type.TypeArguments.Count == 1 => $"RingBuffer<{CSharpType(type.TypeArguments[0])}>",
        "BitSet" => "BitSet",
        "Nil" => "object?",
        "<unknown>" => "object",
        _ when type.TypeArguments.Count == 0 => EscapeIdentifier(type.Name),
        _ => $"{EscapeIdentifier(type.Name)}<{string.Join(", ", type.TypeArguments.Select(CSharpType))}>"
    };

    private static string DefaultValue(VelaType type) => type.Name switch
    {
        "Int" => "0L",
        "Float" => "0d",
        "Bool" => "false",
        "Text" => "string.Empty",
        _ => "default!"
    };

    private static string FormatGenericParameterNames(string[] names) => names.Length == 0
        ? string.Empty
        : $"<{string.Join(", ", names.Select(EscapeIdentifier))}>";

    private static string QuoteString(string value)
    {
        var builder = new StringBuilder(value.Length + 2);
        builder.Append('"');
        foreach (var character in value)
        {
            _ = character switch
            {
                '\\' => builder.Append("\\\\"),
                '"' => builder.Append("\\\""),
                '\n' => builder.Append("\\n"),
                '\r' => builder.Append("\\r"),
                '\t' => builder.Append("\\t"),
                _ when char.IsControl(character) => builder.Append("\\u").Append(((int)character).ToString("x4", CultureInfo.InvariantCulture)),
                _ => builder.Append(character)
            };
        }

        builder.Append('"');
        return builder.ToString();
    }

    private static string EscapeIdentifier(string identifier) => CSharpKeywords.Contains(identifier) ? $"@{identifier}" : identifier;

    private void Report(string code, TextSpan span, string message, string? help = null) => _diagnostics.ReportError(code, span, message, help);

    private sealed record ExpressionResult(VelaType Type, string Code);

    private sealed record VariableSymbol(VelaType Type, bool Mutable);

    private sealed record FunctionSymbol(FunctionDeclarationSyntax Syntax)
    {
        public string[] GenericNames { get; } = Syntax.GenericParameters.Select(static parameter => parameter.Identifier.Text).ToArray();
    }

    private sealed record RecordSymbol(RecordDeclarationSyntax Syntax)
    {
        public string[] GenericNames { get; } = Syntax.GenericParameters.Select(static parameter => parameter.Identifier.Text).ToArray();
    }

    private sealed class Scope(Scope? parent)
    {
        private readonly Dictionary<string, VariableSymbol> _variables = new(StringComparer.Ordinal);

        public bool TryAdd(string name, VariableSymbol symbol) => _variables.TryAdd(name, symbol);

        public bool TryLookup(string name, out VariableSymbol symbol)
        {
            if (_variables.TryGetValue(name, out symbol!))
            {
                return true;
            }

            return parent is not null && parent.TryLookup(name, out symbol!);
        }
    }
}
