using System.Globalization;
using System.Text;

namespace Vela.Backend.Abi;

/// <summary>Writes a deterministic C11 header for a Vela native ABI manifest.</summary>
public static class VelaAbiHeaderWriter
{
    /// <summary>Generates a C11 header describing the exported symbols in <paramref name="manifest"/>.</summary>
    public static string Write(VelaAbiManifest manifest)
    {
        ArgumentNullException.ThrowIfNull(manifest);
        var guard = $"VELA_ABI_{Sanitize(manifest.Package).ToUpperInvariant()}_H";
        var builder = new StringBuilder();
        builder.AppendLine("/* Generated by Vela — do not edit. */");
        builder.AppendLine(CultureInfo.InvariantCulture, $"#ifndef {guard}");
        builder.AppendLine(CultureInfo.InvariantCulture, $"#define {guard}");
        builder.AppendLine();
        builder.AppendLine("#include <stdint.h>");
        builder.AppendLine("#include <stddef.h>");
        builder.AppendLine();
        builder.AppendLine("typedef struct vela_text { const char* data; size_t length; } vela_text;");
        builder.AppendLine("typedef struct vela_decimal { int32_t lo; int32_t mid; int32_t hi; int32_t flags; } vela_decimal;");
        builder.AppendLine("typedef int32_t vela_status;");
        builder.AppendLine();
        builder.AppendLine(CultureInfo.InvariantCulture, $"/* package: {manifest.Package} v{manifest.Version} abi={manifest.AbiVersion} */");
        foreach (var exportItem in manifest.Exports.OrderBy(static item => item.Symbol, StringComparer.Ordinal))
        {
            var returnType = ToCType(exportItem.ReturnType);
            var parameters = exportItem.Parameters.Count == 0
                ? "void"
                : string.Join(", ", exportItem.Parameters.Select((type, index) => $"{ToCType(type)} arg{index.ToString(CultureInfo.InvariantCulture)}"));
            builder.AppendLine(CultureInfo.InvariantCulture, $"{returnType} {exportItem.Symbol}({parameters});");
        }

        builder.AppendLine();
        builder.AppendLine(CultureInfo.InvariantCulture, $"#endif /* {guard} */");
        return builder.ToString();
    }

    private static string ToCType(string velaType) => velaType switch
    {
        "Bool" => "uint8_t",
        "Int" => "int32_t",
        "UInt" => "uint32_t",
        "Long" => "int64_t",
        "Float" => "float",
        "Double" => "double",
        "Decimal" => "vela_decimal",
        "Text" => "vela_text",
        "Unit" => "void",
        _ => "void*"
    };

    private static string Sanitize(string value) =>
        new(value.Select(static character => char.IsLetterOrDigit(character) ? character : '_').ToArray());
}
