namespace Vela.Core.Lexing;

public enum TokenKind
{
    BadToken,
    EndOfFile,
    NewLine,

    Identifier,
    IntegerLiteral,
    FloatLiteral,
    StringLiteral,

    LetKeyword,
    VarKeyword,
    FnKeyword,
    RecordKeyword,
    IncludeKeyword,
    PublicKeyword,
    FfiKeyword,
    ClassKeyword,
    StructKeyword,
    InterfaceKeyword,
    ImplementsKeyword,
    AsKeyword,
    ReturnKeyword,
    AssertKeyword,
    IfKeyword,
    ElseKeyword,
    ForKeyword,
    InKeyword,
    TrueKeyword,
    FalseKeyword,
    NilKeyword,

    Plus,
    Minus,
    Star,
    Slash,
    Equals,
    EqualsEquals,
    BangEquals,
    Less,
    LessOrEqual,
    Greater,
    GreaterOrEqual,
    Arrow,
    Colon,
    Comma,
    Semicolon,
    Dot,
    Question,
    LeftParen,
    RightParen,
    LeftBracket,
    RightBracket,
    LeftBrace,
    RightBrace
}
